def counting_sort(arr):  # O(n + k)
    max_value = max(arr)  # O(n) 
    frequencies = [0] * (max_value + 1)  # O(k) 
    sorted_array = [0] * len(arr)  # O(n) 
    for value in arr:  # O(n)
        frequencies[value] += 1  # O(1)
    total = 0  # O(1)
    for i in range(len(frequencies)):  # O(k)
        total += frequencies[i]  # O(1)
        frequencies[i] = total  # O(1)
    for value in arr:  # O(n) 
        index = frequencies[value] - 1  # O(1)
        sorted_array[index] = value  # O(1)
        frequencies[value] -= 1  # O(1)
    return sorted_array  # O(1)
